Eknorr/initial setup (#2)
* Chore: Fix formatting

* Feature: Add run on condition

* Chore: Update formatting

* Feature: Update var strategy

* Chore: Try something from the internet

* Chore: Try something from the internet

* Chore: Try something from the internet

* Chore: Try something from the internet

* Feature: Add branding

* Test: Use branch name for now

* Test: Actual branch name

* Feature: Add integration test

* Chore: Update integration test

* Test: Update test case

* Feature: Update action.aml with proper inputs

* Test: Removing failure condition

* Test: Add lint outcome var

* Test: Add always()

* Test: Add always()

* Test: Update failure condition

* Feature: Add good test

* Feature: Add actual good test

* Chore: Update test for completion

* Test: update tests

* Test: update tests

* Test: Switch test cases to make sure it fails

* Feature: Fix tests

* Feature: Fix tests

* Chore: Undo test switch

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -2,14 +2,50 @@ name: Integration Test
 
 on:
   push:
-    branches: [main]
 
 jobs:
-  lint-test-json:
+  test-bad-json:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - name: Self test
-        uses: ia-eknorr/ignition-lint@main
+      - name: Test failure case
+        id: lint
+        uses: ia-eknorr/ignition-lint@eknorr/initial-setup
         with:
-          files: ./tests/integration/view.json
+          files: ./tests/integration/bad/view.json
+        continue-on-error: true 
+      - name: Assert test failure
+        run: |
+          if [ ${{ env.LINT_OUTCOME }} == 'failure' ]; then
+            echo "Test Passed (expected)"
+            exit 0
+          else
+            echo "Test Failed (expected)"
+            exit 1
+          fi
+        continue-on-error: false
+        env:
+          LINT_OUTCOME: ${{ steps.lint.outcome }}
+
+  test-good-json:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Test success case
+        id: lint
+        uses: ia-eknorr/ignition-lint@eknorr/initial-setup
+        with:
+          files: ./tests/integration/good/view.json
+        continue-on-error: true 
+      - name: Assert test success
+        run: |
+          if [ ${{ env.LINT_OUTCOME }} == 'success' ]; then
+            echo "Test Passed (expected)"
+            exit 0
+          else
+            echo "Test Failed (expected)"
+            exit 1
+          fi
+        continue-on-error: false
+        env:
+          LINT_OUTCOME: ${{ steps.lint.outcome }}
